/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_sentchart_math_NativeMath */

#ifndef _Included_dev_sentchart_math_NativeMath
#define _Included_dev_sentchart_math_NativeMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_sentchart_math_NativeMath
 * Method:    calculateFFT
 * Signature: (D[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_dev_sentchart_math_NativeMath_calculateFFT
  (JNIEnv *, jclass, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
